test(){
  `$1`
  make -j`nproc`
  if [ $? -ne 0 ]; then
    echo "failed"
    exit(0)
  else
}
mkdir output && cd output
test "cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_JEMALLOC=OFF -DWITH_TESTS=ON -DWITH_TOOLS=ON -DWITH_ASAN=ON -DWITH_TERARK_ZIP=OFF -DWITH_TERARKDB_NAMESPACE:STRING=bytedance .."
test "cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_JEMALLOC=ON -DWITH_TESTS=ON -DWITH_TOOLS=ON -DWITH_ASAN=OFF -DWITH_TERARK_ZIP=ON -UWITH_TERARKDB_NAMESPACE .."
test "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_JEMALLOC=OFF -DWITH_TESTS=ON -DWITH_TOOLS=ON -DWITH_ASAN=ON -DWITH_TERARK_ZIP=OFF -DWITH_TERARKDB_NAMESPACE:STRING=bytedance .."
test "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_JEMALLOC=ON -DWITH_TESTS=OFF -DWITH_TOOLS=ON -DWITH_ASAN=OFF -DWITH_TERARK_ZIP=ON -UWITH_TERARKDB_NAMESPACE .."
test "cmake -DCMAKE_BUILD_TYPE=Release -DWITH_JEMALLOC=OFF -DWITH_TESTS=OFF -DWITH_TOOLS=ON -DWITH_ASAN=ON -DWITH_TERARK_ZIP=OFF -DWITH_TERARKDB_NAMESPACE:STRING=bytedance .."
test "cmake -DCMAKE_BUILD_TYPE=Release -DWITH_JEMALLOC=ON -DWITH_TESTS=OFF -DWITH_TOOLS=OFF -DWITH_ASAN=OFF -DWITH_TERARK_ZIP=ON -UWITH_TERARKDB_NAMESPACE .."
