make LINK_TERARK=static BMI2=1 DISABLE_WARNING_AS_ERROR=1 DEBUG_LEVEL=2 $1 -j && ./$@
make J=1 LINK_TERARK=static BMI2=1 COMPILE_WITH_ASAN=1 DEBUG_LEVEL=2 DISABLE_WARNING_AS_ERROR=1 check -j && ./$@

