name: Build

on:
  pull_request:
    branches: 
      - master
      - dev.*

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: |
        sudo apt-get install -y libaio-dev
        git submodule update --init --recursive
        cmake -E make_directory build

    - name: CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTS=ON -DWITH_TOOLS=ON

    - name: Build
      working-directory: build
      run: make

    - name: Test
      working-directory: build
      run: make test
