name: Build

on:
  pull_request:
    branches:
      - master
      - dev.*
  push:
    branches:
      - master
      - dev.*

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: |
        sudo apt-get update -yy
        sudo apt-get install -f libaio-dev cmake autoconf -yy
        git submodule update --init --recursive

    - name: Create Build Directory
      run: cmake -E make_directory build || true
        
    - name: CMake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTS=ON -DWITH_TOOLS=ON

    - name: Build
      working-directory: build
      run: make -j $(nproc)
