name: CMake

on:
  pull_request:
    branches: 
      - master
      - dev.*

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: |
        sudo apt-get install -y libaio-dev
        git submodule update --init --recursive
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_TESTS=ON -DWITH_TOOLS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make -j $(nproc)

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make test
